---
title: com.aspose.tasks.exceptions
second_title: Aspose.Tasks for Java API Reference
description: Contains internal exceptions that can be thrown by the library.
type: docs
weight: 10
url: /java/com.aspose.tasks.exceptions/
---


## Exceptions

| Exception | Description |
| --- | --- |
| [AccessViolationException](../com.aspose.tasks.exceptions/accessviolationexception) | The exception that is thrown when there is an attempt to read or write protected memory. |
| [AmbiguousMatchException](../com.aspose.tasks.exceptions/ambiguousmatchexception) | The exception that is thrown when binding to a member results in more than one member matching the binding criteria. |
| [ApplicationException](../com.aspose.tasks.exceptions/applicationexception) | Serves as the base class for application-defined exceptions. |
| [ArgumentException](../com.aspose.tasks.exceptions/argumentexception) | The exception that is thrown when one of the arguments provided to a method is not valid. |
| [ArgumentNullException](../com.aspose.tasks.exceptions/argumentnullexception) | The exception that is thrown when a null reference is passed to a method that does not accept it as a valid argument. |
| [ArgumentOutOfRangeException](../com.aspose.tasks.exceptions/argumentoutofrangeexception) | The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method. |
| [ArithmeticException](../com.aspose.tasks.exceptions/arithmeticexception) | The exception that is thrown for errors in an arithmetic, casting, or conversion operation. |
| [ArrayTypeMismatchException](../com.aspose.tasks.exceptions/arraytypemismatchexception) | The exception that is thrown when an attempt is made to store an element of the wrong type within an array. |
| [CookieException](../com.aspose.tasks.exceptions/cookieexception) | The exception that is thrown when an error is made adding a Cookie to a CookieContainer. |
| [CryptographicException](../com.aspose.tasks.exceptions/cryptographicexception) | The exception that is thrown when an error occurs during a cryptographic operation. |
| [CryptographicUnexpectedOperationException](../com.aspose.tasks.exceptions/cryptographicunexpectedoperationexception) | The exception that is thrown when an unexpected operation occurs during a cryptographic operation. |
| [DecoderFallbackException](../com.aspose.tasks.exceptions/decoderfallbackexception) | The exception that is thrown when a decoder fallback operation fails. |
| [DirectoryNotFoundException](../com.aspose.tasks.exceptions/directorynotfoundexception) | The exception that is thrown when part of a file or directory cannot be found. |
| [DivideByZeroException](../com.aspose.tasks.exceptions/dividebyzeroexception) | The exception that is thrown when there is an attempt to divide an integral value by zero. |
| [EncoderFallbackException](../com.aspose.tasks.exceptions/encoderfallbackexception) | The exception that is thrown when an encoder fallback operation fails. |
| [EndOfStreamException](../com.aspose.tasks.exceptions/endofstreamexception) | The exception that is thrown when reading is attempted past the end of a stream. |
| [Exception](../com.aspose.tasks.exceptions/exception) | Represents errors that occur during application execution. |
| [ExternalException](../com.aspose.tasks.exceptions/externalexception) | The base exception type for all COM interop exceptions and structured exception handling (SEH) exceptions. |
| [FieldAccessException](../com.aspose.tasks.exceptions/fieldaccessexception) | The exception that is thrown when there is an invalid attempt to access a private or protected field inside a class. |
| [FileNotFoundException](../com.aspose.tasks.exceptions/filenotfoundexception) | The exception that is thrown when an attempt to access a file that does not exist on disk fails. |
| [FormatException](../com.aspose.tasks.exceptions/formatexception) | The exception that is thrown when the format of an argument is invalid, or when a composite format string is not well formed. |
| [IndexOutOfRangeException](../com.aspose.tasks.exceptions/indexoutofrangeexception) | The exception that is thrown when an attempt is made to access an element of an array or collection with an index that is outside its bounds. |
| [InvalidCastException](../com.aspose.tasks.exceptions/invalidcastexception) | The exception that is thrown for invalid casting or explicit conversion. |
| [InvalidDataException](../com.aspose.tasks.exceptions/invaliddataexception) | The exception that is thrown when a data stream is in an invalid format. |
| [InvalidEnumArgumentException](../com.aspose.tasks.exceptions/invalidenumargumentexception) | The exception that is thrown when an invalid enumeration value is used. |
| [InvalidOperationException](../com.aspose.tasks.exceptions/invalidoperationexception) | The exception that is thrown when a method call is invalid for the object's current state. |
| [InvalidPrinterException](../com.aspose.tasks.exceptions/invalidprinterexception) | Represents the exception that is thrown when you try to access a printer using printer settings that are not valid. |
| [IOException](../com.aspose.tasks.exceptions/ioexception) | The exception that is thrown when an I/O error occurs. |
| [KeyNotFoundException](../com.aspose.tasks.exceptions/keynotfoundexception) | The exception that is thrown when the key specified for accessing an element in a collection does not match any key in the collection. |
| [MemberAccessException](../com.aspose.tasks.exceptions/memberaccessexception) | The exception that is thrown when an attempt to access a class member fails. |
| [MissingManifestResourceException](../com.aspose.tasks.exceptions/missingmanifestresourceexception) | The exception that is thrown if the package does not contain the resources for the neutral culture. |
| [MulticastNotSupportedException](../com.aspose.tasks.exceptions/multicastnotsupportedexception) | The exception that is thrown when there is an attempt to combine two delegates based on the Delegate type instead of the MulticastDelegate type. |
| [NotImplementedException](../com.aspose.tasks.exceptions/notimplementedexception) | The exception that is thrown when a requested method or operation is not implemented. |
| [NotSupportedException](../com.aspose.tasks.exceptions/notsupportedexception) | The exception that is thrown when an invoked method is not supported, or when there is an attempt to read, seek, or write to a stream that does not support the invoked functionality. |
| [NullReferenceException](../com.aspose.tasks.exceptions/nullreferenceexception) | The exception that is thrown when there is an attempt to dereference a null object reference. |
| [ObjectDisposedException](../com.aspose.tasks.exceptions/objectdisposedexception) | The exception that is thrown when an operation is performed on a disposed object. |
| [OperationCanceledException](../com.aspose.tasks.exceptions/operationcanceledexception) | The exception that is thrown in a thread upon cancellation of an operation that the thread was executing. |
| [OutOfMemoryException](../com.aspose.tasks.exceptions/outofmemoryexception) | The exception that is thrown when there is not enough memory to continue the execution of a program. |
| [OverflowException](../com.aspose.tasks.exceptions/overflowexception) | The exception that is thrown when an arithmetic, casting, or conversion operation in a checked context results in an overflow. |
| [ProtocolViolationException](../com.aspose.tasks.exceptions/protocolviolationexception) | The exception that is thrown when an error is made while using a network protocol. |
| [RankException](../com.aspose.tasks.exceptions/rankexception) | The exception that is thrown when an array with the wrong number of dimensions is passed to a method. |
| [SecurityException](../com.aspose.tasks.exceptions/securityexception) | The exception that is thrown when a security error is detected. |
| [SerializationException](../com.aspose.tasks.exceptions/serializationexception) | The exception thrown when an error occurs during serialization or deserialization. |
| [SocketException](../com.aspose.tasks.exceptions/socketexception) | The exception that is thrown when a socket error occurs. |
| [SynchronizationLockException](../com.aspose.tasks.exceptions/synchronizationlockexception) | The exception that is thrown when a method requires the caller to own the lock on a given Monitor, and the method is invoked by a caller that does not own that lock. |
| [SystemException](../com.aspose.tasks.exceptions/systemexception) | Serves as the base class for system exceptions. |
| [TargetException](../com.aspose.tasks.exceptions/targetexception) | Represents the exception that is thrown when an attempt is made to invoke an invalid target. |
| [TargetInvocationException](../com.aspose.tasks.exceptions/targetinvocationexception) | The exception that is thrown by methods invoked through reflection. |
| [TargetParameterCountException](../com.aspose.tasks.exceptions/targetparametercountexception) | The exception that is thrown when the number of parameters for an invocation does not match the number expected. |
| [ThreadAbortException](../com.aspose.tasks.exceptions/threadabortexception) | The exception that is thrown when a call is made to the Abort(Object) method. |
| [ThreadInterruptedException](../com.aspose.tasks.exceptions/threadinterruptedexception) | The exception that is thrown when a Thread is interrupted while it is in a waiting state. |
| [ThreadStateException](../com.aspose.tasks.exceptions/threadstateexception) | The exception that is thrown when a Thread is in an invalid ThreadState for the method call. |
| [TypeLoadException](../com.aspose.tasks.exceptions/typeloadexception) | The exception that is thrown when type-loading failures occur. |
| [UpaException](../com.aspose.tasks.exceptions/upaexception) | UPA violations will throw this exception. |
| [UriFormatException](../com.aspose.tasks.exceptions/uriformatexception) | The exception that is thrown when an invalid Uniform Resource Identifier (URI) is detected. |
| [WebException](../com.aspose.tasks.exceptions/webexception) | The exception that is thrown when an error occurs while accessing the network through a pluggable protocol. |
| [Win32Exception](../com.aspose.tasks.exceptions/win32exception) | Throws an exception for a Win32 error code. |
| [XmlException](../com.aspose.tasks.exceptions/xmlexception) | Returns detailed information about the last exception. |
| [XmlSchemaException](../com.aspose.tasks.exceptions/xmlschemaexception) | Returns detailed information about the schema exception. |
| [XmlSchemaValidationException](../com.aspose.tasks.exceptions/xmlschemavalidationexception) | Represents the exception thrown when XML Schema Definition Language (XSD) schema validation errors and warnings are encountered in an XML document being validated. |
| [XPathException](../com.aspose.tasks.exceptions/xpathexception) | Provides the exception thrown when an error occurs while processing an XPath expression. |
